# Generated by Django 5.1.2 on 2024-10-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='NIC',
        ),
        migrations.AddField(
            model_name='patient',
            name='Birthday',
            field=models.DateField(default='1970-01-01', null=True),
        ),
    ]
