# Generated by Django 5.1.2 on 2024-10-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('Hospital_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Location', models.CharField(max_length=100)),
                ('Rating', models.FloatField()),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hospitals',
            },
        ),
    ]
