# Generated by Django 5.1.2 on 2024-10-26 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('Record_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Doctor_Name', models.TextField()),
                ('Date', models.DateField()),
                ('Description', models.TextField()),
                ('Diagnosis', models.TextField()),
                ('medicines', models.JSONField(default=list)),
                ('Patient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'db_table': 'medical_records',
            },
        ),
    ]
