# Generated by Django 5.1.2 on 2024-10-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('Session_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Patient_ID', models.BigIntegerField()),
                ('Doctor_ID', models.BigIntegerField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Hospital_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
    ]
